"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { api } from "@/lib/api";
import { formatLibraryDate, isActiveLoan } from "@/lib/dates";
import type { Loan, UserProfile } from "@/lib/types";
import { Icon } from "./icons";
import { EmptyState, PageHeading, Status } from "./ui";

export function AdminLoansClient({ overdueOnly = false }: { overdueOnly?: boolean }) {
  const [loans, setLoans] = useState<Loan[]>([]); const [users, setUsers] = useState<Record<string, UserProfile>>({});
  const [status, setStatus] = useState(overdueOnly ? "OVERDUE" : ""); const [search, setSearch] = useState("");
  const [loading, setLoading] = useState(true); const [pending, setPending] = useState(""); const [error, setError] = useState(""); const [message, setMessage] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); try { const [loanResult, userResult] = await Promise.all([api.allLoans(`?limit=50${status ? `&status=${status}` : ""}`), api.users()]); setLoans(loanResult.items); setUsers(Object.fromEntries(userResult.items.map(user => [user.userId, user]))); } catch (caught) { setError(caught instanceof Error ? caught.message : "Borrow records could not be loaded."); } finally { setLoading(false); } }, [status]);
  useEffect(() => { void load(); }, [load]);
  const visible = useMemo(() => { const term = search.toLowerCase(); return loans.filter(loan => `${loan.bookTitle} ${users[loan.userId]?.name ?? ""} ${users[loan.userId]?.email ?? ""}`.toLowerCase().includes(term)); }, [loans, search, users]);
  async function processReturn(loan: Loan) { setPending(loan.loanId); setError(""); setMessage(""); try { const returned = await api.returnBook(loan.loanId); setLoans(items => overdueOnly ? items.filter(item => item.loanId !== loan.loanId) : items.map(item => item.loanId === returned.loanId ? returned : item)); setMessage(`${loan.bookTitle} was returned for ${users[loan.userId]?.name ?? "the member"}.`); } catch (caught) { setError(caught instanceof Error ? caught.message : "The return could not be processed."); } finally { setPending(""); } }
  return <><PageHeading eyebrow={overdueOnly ? "Needs attention" : "Circulation"} title={overdueOnly ? "Overdue books" : "Borrow records"} description={overdueOnly ? "Review past-due loans and process returned copies." : "Follow every book currently moving through the library."}/>{overdueOnly && <div className="notice"><Icon name="warning"/><div><strong>{visible.length} overdue {visible.length === 1 ? "loan" : "loans"}</strong><p>Overdue status is calculated live from each due date.</p></div></div>}{error && <div className="form-error" role="alert">{error}</div>}{message && <div className="form-notice" role="status">{message}</div>}<div className="admin-tools"><label className="search-box"><Icon name="search"/><input aria-label="Search borrow records" placeholder="Search member or book" value={search} onChange={event => setSearch(event.target.value)}/></label>{!overdueOnly && <select aria-label="Filter loan status" value={status} onChange={event => setStatus(event.target.value)}><option value="">All statuses</option><option value="BORROWED">Borrowed</option><option value="RETURNED">Returned</option><option value="OVERDUE">Overdue</option></select>}</div><section className="panel table-panel">{loading ? <div className="page-loading compact"><span className="auth-spinner"/></div> : visible.length === 0 ? <EmptyState icon="history" title="No borrow records found" copy="Records will appear as members borrow from the catalog."/> : <table><thead><tr><th>Book</th><th>Member</th><th>Borrowed</th><th>Due</th><th>Status</th><th></th></tr></thead><tbody>{visible.map(loan => { const user = users[loan.userId]; return <tr key={loan.loanId}><td><strong>{loan.bookTitle}</strong></td><td><strong>{user?.name ?? "Library member"}</strong><small>{user?.email ?? loan.userId}</small></td><td>{formatLibraryDate(loan.borrowedAt)}</td><td>{formatLibraryDate(loan.dueDate)}</td><td><Status status={loan.status}/></td><td>{isActiveLoan(loan.status) && <button disabled={pending === loan.loanId} onClick={() => processReturn(loan)} className="table-action">{pending === loan.loanId ? "Returning…" : "Process return"}</button>}</td></tr>; })}</tbody></table>}</section></>;
}
