import Link from "next/link";
import { BookCard } from "@/components/ui";
import { Icon } from "@/components/icons";
import { books } from "@/lib/demo";

export default function HomePage() {
  return <>
    <section className="hero"><div className="hero-copy"><span className="eyebrow">A modern home for curious minds</span><h1>Find your next<br/><em>great read.</em></h1><p>Explore a thoughtful collection, borrow in a click, and keep every due date beautifully organized.</p><div className="hero-actions"><Link href="/catalog" className="button button-primary">Explore the collection <Icon name="arrow" size={18}/></Link><Link href="/register" className="button button-quiet">Create an account</Link></div><div className="hero-proof"><div className="avatar-stack"><span>MJ</span><span>AK</span><span>RL</span></div><p><strong>1,200+ readers</strong><br/>discovering something new</p></div></div><div className="hero-art" aria-label="A curated stack of featured books"><div className="art-sun"/><div className="art-book art-book-one"><span>ESSAYS ON<br/>A QUIET LIFE</span><small>NO. 08</small></div><div className="art-book art-book-two"><span>THE WORLD<br/>BETWEEN US</span><small>FICTION</small></div><div className="art-book art-book-three"><span>WILD<br/>GARDENS</span><small>FIELD NOTES</small></div><div className="art-table"/></div></section>
    <section className="home-section"><div className="section-heading"><div><span className="eyebrow">Fresh from the shelves</span><h2>Books worth making<br/>time for.</h2></div><Link href="/catalog">View the whole collection <Icon name="arrow" size={17}/></Link></div><div className="book-grid">{books.slice(0,4).map((book,index)=><BookCard key={book.bookId} book={book} index={index}/>)}</div></section>
    <section className="feature-band"><span className="eyebrow">Everything in its place</span><h2>Your reading life,<br/><em>made simple.</em></h2><div className="feature-grid"><article><span>01</span><Icon name="search" size={28}/><h3>Discover with ease</h3><p>Search by title, author, or ISBN and filter the shelves to find exactly what you need.</p></article><article><span>02</span><Icon name="book" size={28}/><h3>Borrow in a click</h3><p>See real-time availability and reserve your next read without standing in line.</p></article><article><span>03</span><Icon name="clock" size={28}/><h3>Never miss a date</h3><p>Keep due dates, active loans, and your complete reading history in one calm view.</p></article></div></section>
    <section className="home-cta"><div><span className="eyebrow">Your next chapter is waiting</span><h2>Ready to start reading?</h2><p>Create your free library account and meet your next favorite book.</p></div><Link href="/register" className="button button-light">Join Mandstacks today <Icon name="arrow" size={18}/></Link></section>
  </>;
}
